spring.application.name=BE-ProgettoSettimana4
spring.datasource.url=jdbc:postgresql://localhost:5432/BE_ProgettoSettimana4
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true